- name: Copying local files
  ansible.builtin.copy:
    src: "docker"
    dest: "~/shadowsocks_config"
  tags: [nginx, keys, shadowsocks]


- name: Setting .env file
  template:
    src: "env.j2"
    dest: "~/shadowsocks_config/docker/.env"
  tags: [nginx, keys, shadowsocks]


- name: Running nginx
  import_tasks: nginx.yml
  tags: nginx


- name: Running shadowsocks proxy server
  import_tasks: shadowsocks.yml
  tags: shadowsocks
