version: "3.8"
services:

# Nginx server
  nginx:
    hostname: nginx
    restart: always
    container_name: server
    image: umputun/nginx-le:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/shadowsocks_config/certs-data/certs/:/etc/nginx/ssl/:rw
      - ./nginx/default.conf:/etc/nginx/service.conf
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=$ADMIN_EMAIL
      - LE_FQDN=$HOST
    links:
      - wg
      - shadowsocks

# Shadowsocks server
  shadowsocks:
    hostname: shadowsocks
    ports:
    - "9000:9000/tcp"
    - "9000:9000/udp"
    container_name: shadowsocks_container
    image: teddysun/shadowsocks-rust
    restart: always
    volumes:
      - ./shadowsocks/config.json:/etc/shadowsocks-rust/config.json/:rw
      - ~/shadowsocks_config/certs-data/certs/:/data/certs/:rw
  
  wg:
    hostname: wg
    container_name: wg
    image: weejewel/wg-easy
    restart: always
    volumes:
      - ./wg:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      WG_HOST: $IP
      PASSWORD: $ADMIN_PASSWORD
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    

